# Generated by Django 3.0.4 on 2020-03-22 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('quantity', models.CharField(max_length=5)),
            ],
        ),
    ]
